// vip_dash_react/src/App.js
import React, { Component } from 'react';
// import logo from './logo.svg';
import './App.css';
import AlarmWidget from './components/AlarmWidget';

class App extends Component {

  render() {
  

  return (
  <div className="container-fluid" style={{marginTop : "20px"}}>

  <div className="row">
    <div className="col-md-9">
      <div className="row">
        <div className="col-md-12">
          <div className="well" id="map"></div>
        </div>
      </div>
      <div className="row">
        <div className="col-md-4 col-sm-4">
          <div className="well">  
          <h4><b>UPE Network Status</b></h4>    
            <AlarmWidget id="UPE_Net_Status" value="1" trendShape="circle-lg red-circle"/>
            <h5><b>Down</b></h5>
          </div>
        </div>
        <div className="col-md-4 col-sm-4">
          <div className="well">    
            <h5><b>Highest Utilization (Top 5)</b></h5>
            <div id="utilization_chart">
            </div>    
          </div>
        </div>
        <div className="col-md-4 col-sm-4">
          <div className="well">
            <h5><b>Trouble Tickets Stats</b></h5>         
            <div id="tickets_chart">
            </div>    
          </div>
        </div>            
      </div>
    </div>
    <div className="col-md-3 hidden-sm">
      <div className="well">
        <h5><b>Trouble Ticket Statstics</b></h5>
        <h4><b>Service Unavailable - S1</b></h4>
        <AlarmWidget id="tt_S1_count" value="7" trendShape="circle-md red-circle"/>
        <div style={{paddingTop: "20px"}}></div>             
        <h4><b>Service Degraded - S2</b></h4>
        <AlarmWidget id="tt_S2_count" value="10" trendShape="circle-md orange-circle"/>
        <div style={{paddingTop: "20px"}}></div>             
        <h4><b>Non-service affecting - S3</b></h4>   
        <AlarmWidget id="tt_S3_count" value="5" trendShape="circle-md black-circle"/>
      </div>
    </div> 
  </div>
  <div className="row">
    <div className="col-md-5">
      <div className="well" style={{paddingTop: "5px"}}>
        <h5 style={{marginBottom: '0px'}}><b>DSL Circuits Status</b></h5> 
        <div className="row">     
          <div className="col-md-4 col-sm-4">
            <h4><b>Down</b></h4>   
            <AlarmWidget id="DSL_Down" value="11" trendShape="triangle black-triangle"/>
          </div>
          <div className="col-md-4 col-sm-4">
            <h4><b>SW Off</b></h4>   
            <AlarmWidget id="DSL_SW_OFF" value="12" trendShape="triangle red-triangle"/>
          </div>
          <div className="col-md-4 col-sm-4">
            <h4><b>Unknown</b></h4>   
            <AlarmWidget id="DSL_Unknown" value="2" trendShape="triangle orange-triangle"/>          
          </div>  
        </div>    
      </div>
    </div>
    <div className="col-md-7">
      <div className="well" style={{paddingTop: "5px"}}>
        <h5 style={{marginBottom: '0px'}}><b>FTTX Circuits Status</b></h5> 
        <div className="row">     
          <div className="col-md-3 col-sm-3">
            <h4><b>Down</b></h4>   
            <AlarmWidget id="FTTX_Down" value="11" trendShape="triangle invert black-triangle" textOrient="invert"/>                      
          </div>
          <div className="col-md-3 col-sm-3">
            <h4><b>SW Off</b></h4>   
            <AlarmWidget id="FTTX_SW_OFF" value="5" trendShape="triangle invert red-triangle" textOrient="invert"/>   
          </div>
          <div className="col-md-3 col-sm-3">
            <h4><b>Disconntd.</b></h4>   
            <AlarmWidget id="FTTX_Disconnect" value="5" trendShape="triangle invert orange-triangle" textOrient="invert"/>   
          </div>  
          <div className="col-md-3 col-sm-3">
            <h4><b>Never conntd.</b></h4>   
            <AlarmWidget id="FTTX_Never_Connected" value="5" trendShape="triangle invert yellow-triangle" textOrient="invert"/>   
          </div>          
        </div>    
      </div>
    </div>
  </div>

  </div>
    );
  }
}

export default App;

// hajj-mobile/src/app/app.component.ts
import { Alarms } from './interfaces/alarms';
import { AlarmsService } from './services/alarms.service';
import { Component, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'Hajj Mobile dashboard';
  serviceAlarms: Alarms = null;// = {UPEStats: {Down: 0} };

  constructor(alarmsService: AlarmsService) {
    this.getAlarms();
  }

  ngOnInit() {
  }
  
  getAlarms() {
     this.alarmsService.getAlarms().subscribe(
       (data : any) => {this.serviceAlarms = data.alarmsData; console.log(this.serviceAlarms);},
       (error) => console.log("Error fetching alarms:", error)
     )

  }
  


}

<div class="container-fluid" id="mainView" style="margin-top:20px">
	<div class="row">
		<div class="col-md-9">
			<div class="row">
				<div class="col-md-12">
					<div class="well" id="map"></div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 col-sm-4">
					<div class="well">			
						<app-alarm-widget title="UPE Network Status" id="UPE_Net_Status" 
						[alarm-count]="serviceAlarms.UPEStats.Down"></app-alarm-widget>
						<h5><b>Down</b></h5>
					</div>
				</div>
				<div class="col-md-4 col-sm-4">
					<div class="well">		
						<h5><b>Highest Utilization (Top 5)</b></h5>
						<div id="utilization_chart">
						</div>		
					</div>
				</div>
				<div class="col-md-4 col-sm-4">
					<div class="well">
						<h5><b>Trouble Tickets Stats</b></h5>					
						<div id="tickets_chart">
						</div>		

					</div>
				</div>            
			</div>
		</div>
		<div class="col-md-3 hidden-sm">
			<div class="well">
				<h5><b>Trouble Ticket Statstics</b></h5>
				<app-alarm-widget title="Service Unavailable - S1" id="tt_S1_count"></app-alarm-widget>
				<div style="padding-top: 20px;"></div>
				<app-alarm-widget title="Service Degraded - S2" id="tt_S2_count"></app-alarm-widget>				
				<div style="padding-top: 20px;"></div>
				<app-alarm-widget title="Non-service affecting - S3" id="tt_S3_count"></app-alarm-widget>				
			</div>
		</div> 
	</div>
	<div class="row">
		<div class="col-md-5">
			<div class="well" style="padding-top: 5px;">
				<h5 style="margin-bottom: 0px;"><b>DSL Circuits Status</b></h5>	
				<div class="row">			
					<div class="col-md-4 col-sm-4">
						<app-alarm-widget title="Down" id="DSL_Down"></app-alarm-widget>				
					</div>
					<div class="col-md-4 col-sm-4">
						<app-alarm-widget title="SW Off" id="DSL_SW_OFF"></app-alarm-widget>				
					</div>
					<div class="col-md-4 col-sm-4">
						<app-alarm-widget title="Unknown" id="DSL_Unknown"></app-alarm-widget>									
					</div>	
				</div>		
			</div>
		</div>
		<div class="col-md-7">
			<div class="well" style="padding-top: 5px;">
				<h5 style="margin-bottom: 0px;"><b>FTTX Circuits Status</b></h5>	
				<div class="row">			
					<div class="col-md-3 col-sm-3">
					<app-alarm-widget title="Down" id="FTTX_Down"></app-alarm-widget>	
					</div>
					<div class="col-md-3 col-sm-3">
					<app-alarm-widget title="SW Off" id="FTTX_SW_OFF"></app-alarm-widget>	
					</div>
					<div class="col-md-3 col-sm-3">
					<app-alarm-widget title="Disconntd." id="FTTX_Disconnect" ></app-alarm-widget>	
					</div>	
					<div class="col-md-3 col-sm-3">
					<app-alarm-widget title="Never conntd." id="FTTX_Never_Connected"></app-alarm-widget>	
					</div>					
				</div>		
			</div>
		</div>
	</div>
</div>
